contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://devtools-next.vuejs.org/help/contributing
    about: Please read through before making contributions.
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://antfu.me/posts/why-reproductions-are-required
    about: Reproduction is very important for maintainer to help on your issues!
